# Project information
site_name: My Docs
site_url: https://hri123.github.io/My-Docs/
site_author: Hrishikesh
site_description: >-
  My Notes / My Docs / My Information

# Repository
repo_name: hri123/My-Docs
repo_url: https://github.com/hri123/My-Docs

# Theme
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

edit_uri: 'blob/main/docs/'